---
  - name: include disable unneeded services
    include_tasks: services.yml
    when: ansible_distribution == 'Ubuntu'
  - name: include install packages
    include_tasks: install.yml
    when: ansible_distribution == 'Ubuntu'
  - name: include configure dnsmasq
    include_tasks: configure.yml
    when: ansible_distribution == 'Ubuntu'








  - name: update package lists # noqa 503 503
    become: yes
    ansible.builtin.apt:
      update_cache: yes
    when: copy_src.changed
















  - name: stop systemd-resolved service on port 53
    become: true
    ansible.builtin.systemd:
      name: systemd-resolved
      enabled: no
      state: stopped
      masked: yes

  - name: Install dnsmasq
    become: true
    ansible.builtin.package:
      name: dnsmasq
      state: present

  - name: journalconf bearbeiten
    become: true
    ansible.builtin.lineinfile:
      state: present
      path: /etc/systemd/journald.conf
      line: "Storage=persistent"
      create: yes
    notify: journalctl neustarten

  - name: set dnsmasq make dhcp
    become: true
    ansible.builtin.template:
      src: "dnsmasq.conf"
      dest: "/etc/dnsmasq.conf"
    notify: dnsmasq Konfigurationsaenderungen aktivieren

  - name: resolv.conf bearbeiten
    become: true
    ansible.builtin.template:
      src: "resolv.conf"
      dest: "/etc/resolv.conf"
    notify: dnsmasq Konfigurationsaenderungen aktivieren

  - name: set dnsmasq make dns
    become: true
    ansible.builtin.template:
      src: "hosts"
      dest: "/etc/hosts"
    notify: dnsmasq Konfigurationsaenderungen aktivieren
