---
  - name: stop systemd-resolved service
    systemd:
      name: systemd-resolved
      state: stopped

  - name: mask systemd-resolved service
    systemd:
      name: systemd-resolved
      masked: yes
      state: stopped

  - name: templating new resolv.conf
    ansible.builtin.template:
      src: resolv.conf.j2
      dest: "{{ dnsmasq_resolv_file }}"
      backup: yes
    notify: restart dnsmasq
