---
  ntp_server_timezone: "Europe/Berlin" #Zeitzone in der sich der Cpmputer befindet
  ntp_server_driftfile_directory: "/var/lib/ntp" # Ordner für das driftfile
  ntp_server_client_servers: # welche Server sollen befragt werden
    - address: ptbtime1.ptb.de
      options: iburst #optionaler parameter
    - address: ptbtime2.ptb.de
      options: iburst
    - address: ptbtime3.ptb.de
      options: iburst
    - address: time3.google.com
      options: iburst
    - address: ntp0.fau.de
      options: iburst
  ntp_server_daemon_user: ntp # Nutzer + Gruppe für den Dienst
  ntp_server_daemon_group: ntp # Nutzer + Gruppe für den Dienst
