---
telegraf_influxdb_srv_protocol: "http://"
telegraf_smart_pfad_zu_smartctl: "/usr/sbin/smartctl"

telegraf_base_metrics: true
telegraf_apcupsd_metrics: false
telegraf_hddtemp_metrics: false
telegraf_smart_metrics: false
telegraf_x509_metrics: false
telegraf_zfs_metrics: false
telegraf_postgres_metrics: false
telegraf_lm_sensors_metrics: false

  #telegraf_influxdb_srv_fqdn: "grafana.grote.lan"
telegraf_influxdb_srv_port: 8086

telegraf_installieren: false
