---
- name: Ensure dirmngr is installed (gnupg dependency).
  apt:
    name:
      - dirmngr
      - sshpass
    state: present

- name: Add ansible repository.
  apt_repository:
    repo: 'ppa:ansible/ansible'
    update_cache: true

- name: Install Ansible.
  apt:
    name: ansible
    state: "{{ ansible_package_state }}"
