  - name: zfs.conf kopieren
    become: yes
    template:
      src: "zfs.conf"
      dest: "/etc/telegraf/telegraf.d/zfs.conf"
    notify: telegraf_starten_aktivieren
#https://gist.github.com/bartmeuris/41caf0998f38a2fae7cf1ff92cd4a5fa
