  - name: SAMBA installieren
    become: yes
    apt:
      name:
        - samba
        - cifs-utils
        - samba-common
        - samba-common-bin
        - samba-vfs-modules
      state: present

  - name: Erstelle Basisverzeichnis
    become: yes
    file:
      path: " {{ smb_base_folder }}"
      state: directory

  - name: Erstelle Linux-Gruppen # vat /etc/group  #kommt aus vars im playbook
    become: yes
    group:
      name: "{{ item.groups }}"
      state: present
    loop: "{{ smb_nutzer }}"
    no_log: True

  - name: Erstelle Linux-Nutzer #kommt aus vars im playbook
    become: yes
    user:
      name: "{{ item.name }}"
      group: "{{ item.groups }}"
      state: present
    loop: "{{ smb_nutzer }}"
    no_log: True

  - name: "Setze SAMBA-Passwoerter"
    become: yes
    shell: "printf '{{ item.password }}\n{{ item.password }}\n' | smbpasswd -a {{ item.name }}" #pipefail: https://blog.christophersmart.com/2019/09/28/using-pipefail-with-shell-module-in-ansible/
    with_items:
    - "{{ smb_nutzer }}"
    no_log: True

  - name: Loesche alte Linux-Nutzer #kommt aus vars im playbook
    become: yes
    user:
      name: "{{ item.name }}"
      state: absent
    loop: "{{ smb_nutzer_loeschen }}"

  - name: Erstelle Freigabeordner
    become: yes
    file:
      path: /shares/{{ item.ordnername }}
      state: directory
      mode: 0777
    loop: "{{ smb_freigaben }}"

  - name: "Konfiguriere Freigaben"
    become: yes
    template:
      src: smb.conf.j2
      dest: /etc/samba/smb.conf
      validate: 'testparm -s %s'
    with_items:
      - "{{ smb_freigaben }}"
    notify: smbd neustarten
    no_log: True
