---
  ### oefenweb.ufw
  ufw_rules:
    - rule: allow
      to_port: 22
      protocol: tcp
      comment: 'ssh'
  ufw_default_incoming_policy: deny
  ufw_default_outgoing_policy: allow
  ### allgemeine variablen
  file_header: |
    #------------------------------------------------------------------
    #-              This file is managed with ansible!                -
    #------------------------------------------------------------------

  ### ntp-client
  ntp_client_timezone: "Europe/Berlin" #Zeitzone in der sich der Cpmputer befindet
  ntp_client_driftfile_directory: "/var/lib/ntp" # Ordner für das driftfile
  ntp_client_servers: # welche Server sollen befragt werden
    - address: 11.8.43.1
      options: iburst #optionaler parameter
    - address: 11.8.43.2
      options: iburst #optionaler parameter
  ntp_client_daemon_user: ntp # Nutzer + Gruppe für den Dienst
  ntp_client_daemon_group: ntp # Nutzer + Gruppe für den Dienst
  ### mgrote.set_apt_sources
  acng_server: 11.10.31.220
  acng_server_port: 9999
  ### dhcp_server_einrichten
  dhcp_dns_ipaddress: "11.10.31.10"
  gateway: 11.10.31.254
  ntp_server: 11.8.43.1
  dhcp_ranges: # welche ranges  gesetzt werden
    - rangename: "server"
      netaddress: "11.10.31."
      firsthostaddress: "6"
      lasthostaddress: "50"
      leasetime: "12h"
      # erst nach ersten test auskommentieren
      # (keine ahnung wie das verhalten bei zwei dhcp ranges im selben subnetz ist)
#    - rangename: "clients"
#      netaddress: "11.10.31."
#      firsthostaddress: "51"
#      lasthostaddress: "200"
#      leasetime: "12h"
  ### robertdebock.bootstrap
  users:
    - username: root
      password: "{{ lookup('keepass', 'linux_user_root_password_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
      update_password: always
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      servers:
        - g_proxmox
    - username: mg
      password: "{{ lookup('keepass', 'linux_user_mg_password_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
      update_password: always
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDTy/g9yfJie8S9mljaYKjOxh6k1ksMqs3bh43KNBXydtoVpOMOUC2nDvJnDwKnnZhuCrqBMrQ3DLoEwg3HBYYzV4pObLgKSek8EuJSVgz1ckeFBjbDlJq4PcUNmK9YurG1stqffWELbrS+EVs6yAu/RoxNSb2/G4aPEWG4ql+88w== mg@vm-test
      servers:
        - g_proxmox
        - g_jenkins
        - g_acng
        - g_dnsmasq
        - g_ansible
    - username: daniel
      password: "{{ lookup('keepass', 'linux_user_daniel_password_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
      update_password: always
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAuMew12jn9S1sWc1bCNcPbi1lmEbKSdEoxzKHRlO3IOMivDUUIqmqjaml7ZPun7hL+sBCEVSyKiCr5wNR+VWY6e0p/7E3iDlSlD2fpymff1yWqvsnEmzBnRPGUQdpbGmfNciDt+XnF+nvQgxPBf30BR2//cSBeVpXA1289q0mbc8Z7hDctLjvM43NwjHg0g5KSLx8yXL4VVRg0S/e05azyA7IvQFTf2gVu5NC/rKpI8bs63KMJOR5LTDEYq8V7IlrsBjqTihl+gkXK08x9bqYPWucV3Zg3VGtKcun0WvSmNZPLZ2q5uq+VQFrfv7ioqZVur0XLX78fC9Se+1aC/+Mr0YAdle1P3yenUYFXntTIpI9ID9/EiV0x1cW6dreUy98fVjYmriaXeOK3AxkupQq34aEqXgN8/EH7bJfevvlPYf2JlBIr14MovlIN7zU2sJ2xxQ5jg3H8U2datWwgHoOKt9PAJ7eMsiITUe3310RRQcvkZ/vGHI07ZGfNfleC4fBXcLt+mwaup6rq7pgR+7FMICPiEOn21ektScatVRXGTx47JsMS7YjmAY1qOlUoQC8FXQ8Vp7wunitar6WY45iGTZTDnujkhQfZkllXmpzi8OK0cRwPYfyNPMxaadTY9B9U6CMxjpFV3iq5XgrhhOgtIZfCkW9cX5A7XXy0xXdvQ== user@Acer5
      servers:
        - g_proxmox
        - g_jenkins
        - g_acng
        - g_dnsmasq
        - g_ansible
    - username: max
      password: "{{ lookup('keepass', 'linux_user_max_password_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
      update_password: always
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXGE+OnkP5+fkUAH7pmDSSYkfp+LixFbGA8XKP7+Ew1XaJ5COM4b3OWzk+sthU724zfom5vCcroeImeukQpQVjJfFfPLTMkNWluTqc9Hvar7OqqggSvSuEasl8MiUlptCxNAKHG1uUkoacerQR1aXnZnvzvwvnWkwYMeB7lhswr81c/kNGptxsXn0gYsjpLYtyFlX7C0iFkd7KDLSnQ6vyFmd5lIjbCjLMYyewEtqgTcEMR3YFCqe7coJ6mMIl7CrqZF+f8D4m1cCZXJgIouIrlYjuUtqbgYjKXEIHbUyBsRAQy4J6YxADBaA1oDy8XbVNrglFqQZIeZ8sbo0MJVFX max@DESKTOP-2FNLGMV
      servers:
        - g_proxmox
        - g_jenkins
        - g_acng
        - g_dnsmasq
        - g_ansible
    - username: kati
      password: "{{ lookup('keepass', 'linux_user_kati_password_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
      update_password: always
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYRBfF/yw28UVkxXPMi8sRRCawSPgBTBE4I+MkMB1gSQXUL1Kv0IRA9QyFB3HD7cJ0q8TiscwV+RVOEJbPepujPVUbR4Xmo8mgTgVHFDgJt1ipTNWgjqi5vMsHTP7vAh4AVvDZGk5tLDiRsUTrAkEpoxFpRcwPDfNymx7+2CNkiqyZKrLEGRA6LKaQrgPy5IBkzOVX7s/xo/WBBdjW7dFsoJKHnecEvwTDLyaGuKkWW/G2kcri7BLhTxwNXkS/PPB06k/fcbfWqo1U0i4caYI4HmeyXVcuxooIbm3D9nAtgtQS3a2yzvv0nLpmT1PjvKPhZ+Y5uUvuEU/5bVZ+Khqt+vPCeNF7+O9sPQJYZ8kJrVLcE16t2/CbnAO7o8wm6s8hfwTpzP7sqUpZdXnsDSW7It7B+YFdgFMLIKlVtSMgL7DrSX8lhSs/jCac/THGCPVt8aDvY48XHA1mANsaaGk15yVt4YioUugZWgT1YYxqCAQFIfEd7veqS9v5UGMS/ekFIn3EG+uZ9YGkvQwLB+9fzQa+g27MHP0kTRgSSnbm1beCf3rK8K4rrGpDr3NIc14g7QhkairCAYeghWkoSYM0R5dztqIoJeNhaCMaYeyTwfiqGXyP6XlR5CNzksR17D6uvMzLQxIZkFC2ynpa1I29cFk0Lar2tEmFoI8UKMLR0Q== kati@DESKTOP-R66MVUO
      servers:
        - g_proxmox
        - g_jenkins
        - g_acng
        - g_dnsmasq
        - g_ansible
    - username: ansible-user
      password: "{{ lookup('keepass', 'linux_user_ansible_password_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
      update_password: on_create
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDaPigi9Q2+eiwYjs32SRqSlBDa3DFY2I2rhFhGHFCDEJYiCTxb8C0FCvgfH5w7MqzyTwJHvrEtsG0VO+xhSsRdq95wsHsDSuiiLP0Zr+pjbpR3IZKwoWiPpfCNBpRlj9X1m+VExhzTEwrIaKD31AfLQ07RvOcamyYZ1ttlODE0f/ALs6/sCeCa14KOaed/IVyGe5hA4vHZirlrzqt+ygwQBLkdvvHymS/Pn1H6JZ15M7SlNdCkJXtPQGOGwlWZr6TH5So0Lppn2cvhSFG8NfxOfaTbLsUy6aBEDPAL+3Q9co/GGFzOydnWLodVpIgG6fXr8qGj/FS9JFT3eEjkCWd2jfEieXsZ0ygzhHMNJ55yeSMD7m/mRW4yqLrgrvDv2aKsyvS8H/kZcoM4/XCTVo1Nf3nivfD/n6xDkTgmqPOjRHgyMZI02CmpCmJWxgf4V67aFeXpDzDwc82fQcFDzxnqBTQCjQnTvF3HqMMTBtXZuGx2jf5oovOBLfFbrNPhFDkBw/oaJxr7d1oUlkXhT7atADZiWKDW64ile4qCy5aPz/F5S9A4vTe9vDYIcxXoIQjVV9QchfF3DxKanp7CZgPpzn0zt40L+7pMkvJLJruCY5B9bh9EYAj+EZXdRD54FY9VJLy8ck+Ckyft35Rqyd6MO+Y6rAEzAwuVVQkdf0/bjQ== Kati@DESKTOP-R66MVUO
      servers:
        - g_proxmox
        - g_jenkins
        - g_acng
        - g_dnsmasq
        - g_ansible
  ### mgrote.install_packages
  install_packages:
    - locales
    - python3
    - build-essential
    - ntp
    - htop
    - git
    - dnsutils
    - nano
    - mc
    - cifs-utils
    - netdiscover
    - tree
    - curl # benötigt für jenkins
    - logrotate
    - ncdu
    - net-tools
    - apt-transport-https
    - ntpdate
    - acl
    - vim
    - qemu-guest-agent
    - bmon
    - sshpass # für ansible
    - tmux
    - sudo

  # Ansible Variablen
  ### User
  ansible_user: "ansible-user"
  #ansible_ssh_pass: "hallowelt"
  ansible_become_pass: "{{ lookup('keepass', 'ansible_become_pass', 'password') }}"
  ### SSH
  ansible_ssh_common_args: "'-o StrictHostKeyChecking=no'"
  host_key_checking: False

  # Ansible Plugin Variablen
  ### Keepass
  # https://github.com/viczem/ansible-keepass
  keepass_dbx: "./keepass_db.kdbx"
  keepass_psw: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66616265623166303430613332396266313037613463393262616565663138623938343166666533
          3663303031636335313234653332613330656635613139300a663662633962613665623734663164
          37353561623430313662376464336539306364363664353239343338303065653830353034336331
          3965646662333930330a363061333538333032343732373431386462623434316363326236613038
          6330
