---
  ### mgrote.paket_installation_update
  programme:
     - locales
     - build-essential
     - ntp
     - htop
     - git
     - python3-pip
     - dnsutils
     - nano
     - mc
     - cifs-utils
     - netdiscover
     - tmux
     - tree
     - qemu-guest-agent
     - curl
     - ncdu
     - net-tools
     - sysstat
     - restic
     - reptyr
     - apt-transport-https
     - cowsay
     - neofetch
     - fortune
     - ntpdate
  ### mgrote.bash_aliases
  bash_aliases:
    - { alias: 'll', command: 'ls -la' }
    - { alias: 'dig', command: 'dig +short ' }
    - { alias: 'tmuxa', command: 'tmux a' }
    - { alias: 'tmuxn', command: 'tmux new -s mg ' }
    - { alias: 'cls', command: 'clear' }
  bash_aliases_path: "/home/mg/.bash_aliases"
  ### mgrote.telegraf
  telegraf_influxdb_srv_fqdn: "grafana.grote.lan"
  telegraf_influxdb_srv_port: 8086 #portangabe muss ohne punkt erfolgen - Pflicht
  telegraf_influxdb_srv_protocol: "http://"
  telegraf_base_metrics: true
  ### mgrote.fileserver_smb
  domain: grote.lan
  nas: fileserver.grote.lan
  ### mgrote.acng
  acng_server: acng.grote.lan #rolle grundinstallation
  acng_server_port: 9999
  ### mgrote.motd
  motd_fortune_aktiv: false
  motd_wetter_aktiv: false
  ### mgrote.set_apt_sources
  paket_mirror_nutzen: true

  # Extras
  ### user fuer ansible
  ansible_user: "ansible-user"
  ### python3
  # https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html
  ansible_python_interpreter: "/usr/bin/python3"
