---
  ### mgrote.set_apt_sources
  acng_server: ws-ubuntu4.grote.lan
  acng_server_port: 9999
  ### robertdebock.bootstrap
  users:
    - username: mg
      password: $6$llUfBmJVYjVc6V$0C8PaatCqxv.uDwTIHHYAOJA89ZbtWNX/lGiP8uFDO5m2HCPIaPhzBovpv8QiaJBfFeDIY/jnix4s0yxuEpDJ. # = hallowelt; mkpasswd --method=SHA-512 --stdin
      update_password: always
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDhCkPnS741TxJLZxYZYoUGlZgcrBDuubyF4VDNufzqajCFrP1y54+IZ4VjRUcvldJwAjUT72FOF/HcCYxckQuBT4PtN+Ys784uwddMFCk3vzPFUrPfP/87vVhRUO1EZHTwv2zQ8BKAZ1tGulOJ1uZRfmiKrb0aqdPuKB9iNixuHzysOvppvAnN7CoNqrvUqc/zMqw2RJRwFMVhsQRKtzwx2haP5xUh7i9JBb2kEG9YhQXTxMKwK9M5iPkWV5Q5RTKzT0stiWKSEOc+km4Rz7HxGaaBbz0V6bMUCc9n+owgWdnyxIqi8k3oii0/rfsnmLP75r+ZjhaP5AeCNSBP5kWoi85Dwq51iSKiuRoKL6lEC8zEYUNtPJkrSG8U8MPpia59O4EF8r+HHuu7mxThJn09QdYWeHco9rCzCD8D3UUS+RLLg4m8c+JPNXZ+6MfpJJhODiJcoZ9glpL2gHRcVi8LjPD0TS41SfFVixOj/Yo5W/gVd8qzzW1lnMsD/FmejAEIhZfFv40rwMmdB3M58Ow9Et/tV2/m6CaYUhcmYZgTWvaKVSS1OTz4DT53b1qqqu8NA+XXFeo4WNC3lvbplolUOpKMUUHHYNjtRIa9LA7RCxHMFt2yJXSbeAsDhx2hbMKUzh+aGo7Oh/NsFcIHajrvBdotkG6imNhocg/AaIAZJw== mg@vm-test

      servers:
        - proxmox
        - ubuntu
    - username: daniel
      password: $6$llUfBmJVYjVc6V$0C8PaatCqxv.uDwTIHHYAOJA89ZbtWNX/lGiP8uFDO5m2HCPIaPhzBovpv8QiaJBfFeDIY/jnix4s0yxuEpDJ. # = hallowelt; mkpasswd --method=SHA-512 --stdin
      update_password: always
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAuMew12jn9S1sWc1bCNcPbi1lmEbKSdEoxzKHRlO3IOMivDUUIqmqjaml7ZPun7hL+sBCEVSyKiCr5wNR+VWY6e0p/7E3iDlSlD2fpymff1yWqvsnEmzBnRPGUQdpbGmfNciDt+XnF+nvQgxPBf30BR2//cSBeVpXA1289q0mbc8Z7hDctLjvM43NwjHg0g5KSLx8yXL4VVRg0S/e05azyA7IvQFTf2gVu5NC/rKpI8bs63KMJOR5LTDEYq8V7IlrsBjqTihl+gkXK08x9bqYPWucV3Zg3VGtKcun0WvSmNZPLZ2q5uq+VQFrfv7ioqZVur0XLX78fC9Se+1aC/+Mr0YAdle1P3yenUYFXntTIpI9ID9/EiV0x1cW6dreUy98fVjYmriaXeOK3AxkupQq34aEqXgN8/EH7bJfevvlPYf2JlBIr14MovlIN7zU2sJ2xxQ5jg3H8U2datWwgHoOKt9PAJ7eMsiITUe3310RRQcvkZ/vGHI07ZGfNfleC4fBXcLt+mwaup6rq7pgR+7FMICPiEOn21ektScatVRXGTx47JsMS7YjmAY1qOlUoQC8FXQ8Vp7wunitar6WY45iGTZTDnujkhQfZkllXmpzi8OK0cRwPYfyNPMxaadTY9B9U6CMxjpFV3iq5XgrhhOgtIZfCkW9cX5A7XXy0xXdvQ== user@Acer5
      servers:
        - proxmox
        - ubuntu
    - username: max
      password: $6$llUfBmJVYjVc6V$0C8PaatCqxv.uDwTIHHYAOJA89ZbtWNX/lGiP8uFDO5m2HCPIaPhzBovpv8QiaJBfFeDIY/jnix4s0yxuEpDJ. # = hallowelt; mkpasswd --method=SHA-512 --stdin
      update_password: always
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      ssh_key:
      servers:
        - proxmox
        - ubuntu
    - username: kati
      password: $6$llUfBmJVYjVc6V$0C8PaatCqxv.uDwTIHHYAOJA89ZbtWNX/lGiP8uFDO5m2HCPIaPhzBovpv8QiaJBfFeDIY/jnix4s0yxuEpDJ. # = hallowelt; mkpasswd --method=SHA-512 --stdin
      update_password: always
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      ssh_key:
      servers:
        - proxmox
        - ubuntu
    - username: ansible-user
      password: $6$llUfBmJVYjVc6V$0C8PaatCqxv.uDwTIHHYAOJA89ZbtWNX/lGiP8uFDO5m2HCPIaPhzBovpv8QiaJBfFeDIY/jnix4s0yxuEpDJ.
      update_password: on_create
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      ssh_key:
      servers:
        - proxmox
        - ubuntu
  ### mgrote.install_packages
  install_packages:
    - locales
    - python3
    - build-essential
    - ntp
    - htop
    - git
    - dnsutils
    - nano
    - mc
    - cifs-utils
    - netdiscover
    - tree
    - curl
    - logrotate
    - ncdu
    - net-tools
    - apt-transport-https
    - ntpdate
    - acl
    - vim



  # Ansible Variablen
  ### User
  ansible_user: "ansible-user"
  ansible_ssh_pass: "hallowelt"
  ansible_become_pass: "hallowelt"
  ### SSH
  ansible_ssh_common_args: "'-o StrictHostKeyChecking=no'"
