---
  ### mgrote.install_packages
  programme:
     - locales
     - build-essential
     - ntp
     - htop
     - git
     - python3-pip
     - dnsutils
     - nano
     - mc
     - cifs-utils
     - netdiscover
     - tmux
     - tree
     - qemu-guest-agent
     - curl
     - ncdu
     - net-tools
     - sysstat
     - restic
     - reptyr
     - apt-transport-https
     - cowsay
     - neofetch
     - fortune
     - ipmitool
     - ntpdate
     - powertop

  ### igor_mukhin.bash_aliases
  bash_aliases:
    - { alias: 'll', command: 'ls -la' }
    - { alias: 'dig', command: 'dig +short ' }
    - { alias: 'tmuxa', command: 'tmux a' }
    - { alias: 'tmuxn', command: 'tmux new -s mg ' }
    - { alias: 'cls', command: 'clear' }
    - { alias: 'df', command: 'df -h' }
  bash_aliases_path: "/home/mg/.bash_aliases"
  ### mgrote.restic
  restic_cron_hours: "19"
  restic_repository: "//fileserver.grote.lan/Backup/restic"
  restic_repository_password: Vl00coPLYbcQPEQK9rOl
  restic_mount: "/mnt/restic"
  restic_mount_user: restic
  restic_mount_password: restic
  ### mgrote.postfix-gmail
  empfaenger_mail: michael.grote@posteo.de
  nutzer_gmail: michael.grote@gmail.com
  passwort_gmail: FKXaOMOPv9bF5kHC
  postfix_gmail_erlaubte_netzwerke: "127.0.0.0/8 192.168.2.0/24"
  ### mgrote.fileserver_smb
  domain: grote.lan
  nas: fileserver.grote.lan
  ### mgrote.acng
  acng_server: acng.grote.lan #rolle grundinstallation
  acng_server_port: 9999
  ### mgrote.motd
  motd_fortune_aktiv: false
  motd_wetter_aktiv: false
  ### mgrote.set_apt_sources
  paket_mirror_nutzen: true

  # Extras
  ### user fuer ansible
  ansible_user: "ansible-user"
  ### python3
  # https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html
  ansible_python_interpreter: "/usr/bin/python3"
