---
  users:
    - username: mg
      password: hallowelt
      update_password: on_create
      use_sudo: yes
      use_sudo_nopass: yes
      user_state: present
      groups: ssh, sudo
      servers:
        - all
