---
  ### dhcp-server einrichten
  dhcp_ranges: # welche ranges sollen gesetzt werden
    - rangename: "server"
      netaddress: "192.168.178."
      firsthostaddress: "5"
      lasthostadrdess: "10"
      leasetime: "12h"
  ### oefenweb.ufw
  ufw_rules:
    - rule: allow
      to_port: 22
      protocol: tcp
      comment: 'ssh'
    - rule: allow
      to_port: 53
      comment: 'dns'
    - rule: allow
      to_port: 67
      comment: 'dhcp'
    - rule: allow
      to_port: 68
      comment: 'dhcp'
