---
  ### oefenweb.ufw
  ufw_rules:
    - rule: allow
      to_port: 22
      protocol: tcp
      from_ip: 11.10.31.0/24
      comment: 'ssh'
    - rule: allow
      to_port: 9999
      from_ip: 11.10.31.0/24
      comment: 'acng'
  ### mgrote.acng
  acng_exthreshold: "60"
  acng_port: "9999"
  acng_security_conf_path: "/etc/apt-cacher-ng/security.conf"
  acng_server_auth_user: aadmin
  acng_server_auth_pass: "{{ lookup('keepass', 'acng_adminauth_password', 'password') }}"
  ### set_apt_proxy
  apt_proxy_server: proxy.ausbildung.md
  apt_proxy_port: 8080
  apt_proxy_apt_conf_path: /etc/apt/apt.conf
