---
  ### oefenweb.ufw
  ufw_rules:
    - rule: allow
      to_port: 22
      protocol: tcp
      from_ip: 11.10.31.0/24
      comment: 'ssh'
    - rule: allow
      to_port: 9999
      from_ip: 11.10.31.0/24
      comment: 'acng'
  ### mgrote.acng
  acng_exthreshold: "60" # Wie lange Pakete gespeichert werden
  acng_port: "9999" # Port f端r acng
  acng_acng_conf_path: "/etc/apt-cacher-ng/acng.conf" # Pfad f端r acng.conf
  acng_security_conf_path: "/etc/apt-cacher-ng/security.conf" # Pfad f端r security conf
  acng_auth_user: aadmin # login user (webinterface)
  acng_auth_pass: "{{ lookup('keepass', 'acng_adminauth_password', 'password') }}" # login passwort (webinterface)
  acng_proxy_extern_ip: "11.8.108.254" # Externe IP Proxy
  acng_proxy_extern_port: "8080" # Externer Port f端r Proxy
  acng_verboselog: "1" # Speichert mehr Infos als im normalen Modus.
  acng_debug: "0" # Speichert mehr Infos bei Fehlern.
