---
  ### geerlingguy.pip
  pip_package: python3-pip
  pip_install_packages:
    - name: pykeepass
      version: "3.2.1"
    - name: Jinja2
      version: "2.11.2"
    - name: markupsafe
  pip_http_proxy: '11.8.108.254:8080'
  pip_https_proxy: '11.8.108.254:8080'
  ### geerlingguy.ansible
  ansible_install_method: pip
  ansible_install_version_pip: '2.10.8'
  ### mgrote.restic
  restic_folders_to_backup: "/usr/local /etc /root /home"
  ### mgrote.apt_install_packages
  programs_extra:
    - sshpass
