---
  ### geerlingguy.mysql
  mysql_root_password: root
  mysql_databases:
    - name: example_db
      encoding: latin1
      collation: latin1_general_ci
  mysql_users:
    - name: example_user
      host: "%"
      password: hallowelt
      priv: "example_db.*:ALL"
