---
  ### geerlingguy.jenkins
  jenkins_package_state: latest
  jenkins_http_port: 8080
  jenkins_admin_username: jadmin
  jenkins_admin_password: "{{ lookup('keepass', 'jenkins_admin_password', 'password') }}"
  jenkins_plugins_install_dependencies: true
  jenkins_plugins_state: latest
  jenkins_java_options: "-Djenkins.install.runSetupWizard=true"
  jenkins_proxy_host: "{{ proxy_ip }}"
  jenkins_proxy_port: "{{ proxy_port }}"
  jenkins_proxy_noproxy:
    - "127.0.0.1"
    - "localhost"
    - "11.10.31.0"
  ### oefenweb.ufw
  ufw_rules:
    - rule: allow
      to_port: 22
      protocol: tcp
      from_ip: 11.10.31.0/24
      comment: 'ssh'
    - rule: allow
      to_port: 8080
      comment: 'jenkins'
      from_ip: 11.10.31.0/24
  ### geerlingguy.pip
  pip_package: python3-pip
  pip_install_packages:
    - name: pykeepass
      version: "3.2.1"
    - name: Jinja2
      version: "2.11.2"
    - name: markupsafe
  pip_http_proxy: '"{{ proxy_ip }}:{{ proxy_port }}"' # für pip und ansible
  pip_https_proxy: '"{{ proxy_ip }}:{{ proxy_port }}"' # für pip und ansible
  ### geerlingguy.ansible
  ansible_install_method: pip
  ansible_install_version_pip: '2.10'
  ### mgrote.apt_install_packages
  programs_extra:
    - sshpass
