  - name: Apt-key hinzufuegen fuer das telegraf-repository
    become: yes
    apt_key:
      url: https://repos.influxdata.com/influxdb.key
      state: present

  - name: telegraf-repository hinzufuegen
    become: yes
    apt_repository:
      repo: 'deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable'
      state: present
      filename: telegraf_repo
      update_cache: yes

  - name: telegraf installieren
    become: yes
    apt:
      name: telegraf
      state: present

  - name: telegraf.conf kopieren
    become: yes
    template:
      src: "telegraf.conf"
      dest: "/etc/telegraf/telegraf.conf"
    notify: telegraf_starten_aktivieren

  - name: add base_metrics tasks
    import_tasks: '{{ role_path }}/tasks/metrics/base_metrics.yml'
    when: telegraf_base_metrics == true

  - name: add apcupsd_metrics tasks
    import_tasks: '{{ role_path }}/tasks/metrics/apcupsd_metrics.yml'
    when: telegraf_apcupsd_metrics == true

  - name: add hddtemp_metrics tasks
    import_tasks: '{{ role_path }}/tasks/metrics/hddtemp_metrics.yml'
    when: telegraf_hddtemp_metrics == true

  - name: add smart_metrics tasks
    import_tasks: '{{ role_path }}/tasks/metrics/smart_metrics.yml'
    when: telegraf_smart_metrics == true

  - name: add x509_metrics tasks
    import_tasks: '{{ role_path }}/tasks/metrics/x509_metrics.yml'
    when: telegraf_x509_metrics == true

  - name: add zfs_metrics tasks
    import_tasks: '{{ role_path }}/tasks/metrics/zfs_metrics.yml'
    when: telegraf_zfs_metrics == true
