---
  - name: restart dnsmasq
    become: yes
    systemd:
      name: dnsmasq
      enabled: yes
      state: restarted

  - name: check config
    become: yes
    ansible.builtin.shell: dnsmasq --test
