---
  dnsmasq_resolv_file: "/etc/resolv.conf" # wo liegt die resolv.conf
  dnsmasq_extra_resolve_file: "/etc/dnsmasq_extra_resolve_file" # wo liegen extra hosts/ersatz fur /etc/hosts
  dnsmasq_packages: # Pakete
    - dnsmasq
    - dnsutils
    - ldnsutils
  dnsmasq_max_leases: "200" # wieviel leases darf dnsmasq gleichzeitig vergeben
  dnsmasq_external_nameserver:  # Welche nameserver soll dnsmasq befragen
    - address: "127.0.0.1" # sonst kann dnsmasq selber nichts auflösen
    - address: "9.9.9.9"
  dnsmasq_listen_port: "53" # auf welchem Port soll dnsmasq hören
  dnsmasq_domain: ausbildung.md # wie heißt die lokale domain
  dnsmasq_dhcp_pools: # welche dhcp pools gibt es
    - name: pool1
      ip_start: 11.10.31.220
      ip_end: 11.10.31.230
      leasetime: "3m"
  dnsmasq_dhcp_static_leases: # statische leases; also max 11:22:33:44:55:66 kriegt immer IP 192.168.0.60 mit dem hostnamen klauspeter
    - name: "klauspeter" # gleichzeitg auch hostname
      mac: "11:22:33:44:55:66"
      ip: "192.168.0.60"
  dnsmasq_dhcp_options: # welche dhcp optionen werden gesetzt
    - name: ntp-server
      optnr: "42"
      value: "11.8.43.1,11.8.43.2"
  dnsmasq_addresses_to_resolve: # namensauflösung für geräte ohne leases
    - shortname: acng
      ip: 11.10.31.220
  dnsmasq_log_dhcp: false # Log lots of extra information about DHCP transactions.
  dnsmasq_log_queries: false # For debugging purposes, log each DNS query as it passes through dnsmasq.
