---
  - hosts: g_ubuntu
    roles:
      - { role: oefenweb.ufw, # Regeln werden in den Group/Host-Vars gesetzt
          tags: "ufw",
          become: true,
          when: "not 'proxmox' in group_names" }
      - deactivate_ssh_password_login
