---
  - hosts: all
    roles:
      - { role: mgrote.set_apt_sources, tags: "sources", become: yes}
      - { role: mgrote.update_packages, tags: "update", become: yes}
      - { role: mgrote.install_packages, tags: "install", become: yes}
      - { role: ntp-client, tags: "ntp", become: yes}
      - { role: ryandaniels.create_users, tags: "user", become: yes}
