---
  programs_common:
    - locales
    - build-essential
    - ntp
    - htop
    - git
    - dnsutils
    - nano
    - mc
    - cifs-utils
    - netdiscover
    - tree
    - curl
    - logrotate
    - tmux
    - ncdu
    - net-tools
    - sysstat
    - apt-transport-https
    - neofetch
    - ntpdate
    - acl
