  - name: zfs-tools installieren
    become: yes
    apt:
      pkg:
        - zfsutils
        - zfs-initramfs
        - zfs-zed
      state: present

  - name: Limit ZFS Memory Usage
    become: yes
    lineinfile:
      path: /etc/modprobe.d/zfs.conf
      line: options zfs zfs_arc_max={{ zfs_arc_max }}
      create: yes

  - name: erstelle Ordner "root-zfs"
    become: yes
    file:
      path: /root/zfs
      state: directory

  - name: kopiere "zfs-health.sh"
    become: yes
    template:
      src: zfs-health.sh
      dest: /root/zfs/zfs-health.sh
      mode: "+x"

  - name: lege cronjob fuer "zfs-health.sh" an
    become: yes
    cron:
      name: zfs-health
      state: present
      job: "/root/zfs/zfs-health.sh"
      minute: "{{ cron_minutes_zfs_health }}"

  - name: lege cronjob fuer "zfs-scrub" an
    become: yes
    cron:
      name: zfs-scrub - "{{ item.name }}"
      state: present
      job: "{{ pfad_zu_zpool }} scrub {{ item.name }}"
      weekday: "{{ item.cron_weekday_zfs_scrub }}"
      minute: "{{ item.cron_minutes_zfs_scrub }}"
      hour: "{{ item.cron_hour_zfs_scrub }}"
    with_items: "{{ zfs_pool }}"

  - name: lege cronjob fuer "zfs-trim" an
    become: yes
    cron:
      name: zfs-trim - "{{ item.name }}"
      state: present
      job: "{{ pfad_zu_zpool }} trim {{ item.name }}"
      minute: "{{ item.cron_minute_zfs_trim }}"
      hour: "{{ item.cron_hour_zfs_trim }}"
      month: "{{ item.cron_month_zfs_trim }}"
      day: "{{ item.cron_day_zfs_trim }}"
    with_items: "{{ zfs_pool }}"

  - name: kopiere zed.rc
    become: yes
    template:
      src: zed.rc
      dest: /etc/zfs/zed.d/zed.rc
    notify: testmail
