---
- hosts: ansible
  roles:
    - { role: mgrote.set_apt_sources, tags: "apt_sources" }
    - { role: mgrote.create_users, tags: "users" }
    - { role: mgrote.set_timezone, tags: "timezone" }
    - { role: mgrote.motd, tags: "motd" }
    - { role: mgrote.paket_installation_update, tags: "updates" }
    - { role: mgrote.telegraf, tags: "telegraf" }
    - { role: mgrote.restic, tags: "restic" }
    - { role: igor_mukhin.bash_aliases, tags: "aliases" }
    - { role: mgrote.ansible_host, tags: "ansible_host" }
