---
  all:
    children:
      proxmox:
        hosts:
          RMPHLPVE1:
            ansible_host: 11.10.31.11
          RMPHLPVE2:
            ansible_host: 11.10.31.12
      ubuntu:
        hosts:
          acng:
            ansible_host: 11.10.31.220
          ansible:
            ansible_host: 11.10.31.221
          dnsmasq:
            ansible_host: 11.10.31.10
      dhcp:
        hosts:
          dnsmasq:
            ansible_host: 11.10.31.10
      ansible:
        hosts:
          ansible:
            ansible_host: 11.10.31.221
      acng:
        hosts:
          acng:
            ansible_host: 11.10.31.220
      g_jenkins:
        hosts:
          h_jenkins:
            ansible_host: 11.10.31.223
      ntpserver:
        hosts:
      database:
        hosts:
