  - name: apt update
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 300

  - name: install packages
    become: yes
    apt:
      name: "{{ install_packages }}"
      state: present
